# Generated by Django 5.2.4 on 2025-09-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief description of the blog'),
        ),
    ]
