# Generated by Django 5.2.6 on 2025-09-22 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accomplishment_json',
            field=models.JSONField(blank=True, default=dict, help_text='Accomplishments in JSON format'),
        ),
        migrations.AddField(
            model_name='profile',
            name='community_json',
            field=models.JSONField(blank=True, default=dict, help_text='Community information in JSON format'),
        ),
        migrations.AddField(
            model_name='profile',
            name='family_json',
            field=models.JSONField(blank=True, default=dict, help_text='Family information in JSON format'),
        ),
        migrations.AddField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(blank=True, help_text='User-provided joined date', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_experience_json',
            field=models.JSONField(blank=True, default=dict, help_text='Professional experience in JSON format'),
        ),
        migrations.CreateModel(
            name='ChildhoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='childhood_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childhood_images', to='user.profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
