# Generated by Django 5.2.6 on 2025-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_accomplishment_json_profile_community_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.AddField(
            model_name='profile',
            name='education_json',
            field=models.JSONField(blank=True, default=dict, help_text='Education information in JSON format'),
        ),
    ]
