# Generated by Django 5.1.4 on 2025-10-14 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_education_profile_education_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accomplishment_json',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='community_json',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='early_childhood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education_json',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='family_json',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='professional_experience_json',
        ),
        migrations.AddField(
            model_name='profile',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Array of profile sections'),
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text='ID of the section this image belongs to', max_length=100)),
                ('image', models.ImageField(upload_to='section_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_images', to='user.profile')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['profile', 'section_id'], name='user_sectio_profile_8fdab7_idx')],
            },
        ),
    ]
