# Generated by Django 5.1.4 on 2025-10-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_accomplishment_json_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChildhoodImage',
        ),
    ]
