# Generated by Django 5.1.4 on 2026-06-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_gender_user_is_invited_familyrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth", null=True),
        ),
    ]
