# Generated by Django 5.1.4 on 2026-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Date of death (optional)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deceased',
            field=models.BooleanField(default=False, help_text='True if this registered user has been marked as deceased'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deceased',
            field=models.BooleanField(default=False, help_text='True for deceased placeholder accounts with no real user'),
        ),
    ]
