# Generated by Django 5.1.4 on 2026-06-04 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_add_deceased_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyrelationship',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL),
        ),
    ]
